"""add business type capabilities paypal config and order metadata

Revision ID: 01e4fef4ab41
Revises:
Create Date: 2026-09-14 18:46:57.950488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e4fef4ab41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_payment_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paypal_client_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paypal_client_secret_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('paypal_mode', sa.String(length=20), nullable=True))

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('capabilities', sa.JSON(), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('capabilities')
        batch_op.drop_column('business_type')

    with op.batch_alter_table('business_payment_configs', schema=None) as batch_op:
        batch_op.drop_column('paypal_mode')
        batch_op.drop_column('paypal_client_secret_encrypted')
        batch_op.drop_column('paypal_client_id')
        batch_op.drop_column('paypal_email')

    # ### end Alembic commands ###
